language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
 - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r Springboot_Book *
  - mkdir -p deploy
  - mv Springboot_Book.zip deploy/Springboot_Book.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot2-build-book # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot2-build-book # S3 버킷
    key: Springboot_Book.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: springboot2-webservice-book # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot2-webservice-book-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹 >>그룹 설정 변경
    region: ap-northeast-2
    wait-until-deployed: true

    # ruby 오류 확인으로, 업데이트 후 재시도
    #aws - sdk 설치 update 완료

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - xowjd41@gmail.com